# frozen_string_literal: true

module Keystone
  # Complete list of Tailwind CSS classes used by all Keystone components.
  # Tailwind v4 does not process @source directives in imported CSS files,
  # so the install generator writes this as @source inline("...") directly
  # into the host app's application.css.
  #
  # Keep in sync with component constants and templates.
  # Run `bundle exec rspec spec/keystone/safelist_spec.rb` to verify.
  SAFELIST = "-mr-1.5 -mt-1.5 bg-blue-50 bg-gray-50 bg-gray-500 bg-green-50 bg-indigo-600 bg-red-50 bg-red-600 bg-white bg-yellow-50 block border border-0 border-gray-200 border-gray-300 border-y cursor-not-allowed cursor-pointer dark:bg-blue-900/30 dark:bg-gray-800/50 dark:bg-gray-800/75 dark:bg-green-900/30 dark:bg-red-900/30 dark:bg-yellow-900/30 dark:bg-zinc-800 dark:bg-zinc-900 dark:border-zinc-700 dark:divide-white/10 dark:divide-white/15 dark:focus:border-indigo-400 dark:focus:ring-indigo-400 dark:hover:text-indigo-300 dark:placeholder:text-gray-500 dark:shadow-none dark:text-blue-300 dark:text-gray-200 dark:text-gray-300 dark:text-gray-400 dark:text-green-300 dark:text-indigo-400 dark:text-red-300 dark:text-red-400 dark:text-white dark:text-yellow-300 divide-gray-200 divide-gray-300 divide-y flex flex-1 flex-shrink-0 focus:border-indigo-500 focus:outline-none focus:ring-1 focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 font-bold font-medium font-semibold gap-3 gap-4 gap-6 gap-8 gap-x-3 gap-x-4 gap-x-6 gap-x-8 gap-y-3 gap-y-4 gap-y-6 gap-y-8 grid grid-cols-1 grid-cols-10 grid-cols-11 grid-cols-12 grid-cols-2 grid-cols-3 grid-cols-4 grid-cols-5 grid-cols-6 grid-cols-7 grid-cols-8 grid-cols-9 hidden hover:bg-gray-400 hover:bg-indigo-500 hover:bg-red-500 hover:text-indigo-900 hover:border-indigo-500 inline-flex items-center justify-between justify-center lg:grid-cols-1 lg:grid-cols-10 lg:grid-cols-11 lg:grid-cols-12 lg:grid-cols-2 lg:grid-cols-3 lg:grid-cols-4 lg:grid-cols-5 lg:grid-cols-6 lg:grid-cols-7 lg:grid-cols-8 lg:grid-cols-9 lg:px-8 m-0 max-w-2xl max-w-4xl max-w-6xl max-w-7xl mb-0 mb-4 mb-6 md:grid-cols-1 md:grid-cols-10 md:grid-cols-11 md:grid-cols-12 md:grid-cols-2 md:grid-cols-3 md:grid-cols-4 md:grid-cols-5 md:grid-cols-6 md:grid-cols-7 md:grid-cols-8 md:grid-cols-9 min-w-full ml-0.5 ml-auto mt-1 mt-4 mt-6 mt-8 mx-auto no-underline overflow-hidden p-1.5 p-3 p-4 p-5 p-6 pb-4 pl-3 pl-6 placeholder:text-gray-400 pr-3 pr-6 px-3 px-4 px-5 py-1.5 py-2 py-3 py-3.5 py-4 relative rounded-2xl rounded-lg rounded-md rounded-xl shadow-sm sm:border-x sm:flex sm:grid-cols-1 sm:grid-cols-10 sm:grid-cols-11 sm:grid-cols-12 sm:grid-cols-2 sm:grid-cols-3 sm:grid-cols-4 sm:grid-cols-5 sm:grid-cols-6 sm:grid-cols-7 sm:grid-cols-8 sm:grid-cols-9 sm:items-center sm:justify-between sm:ml-4 sm:mt-0 sm:pb-4 sm:pb-6 sm:pt-6 sm:px-6 sm:rounded-lg sm:table-cell space-y-1 text-2xl text-base text-blue-800 text-gray-500 text-gray-700 text-gray-900 text-green-800 text-indigo-600 text-left text-lg text-red-500 text-red-600 text-red-800 text-right text-sm text-white text-yellow-800 w-full whitespace-nowrap"
end
